### ISSUE TITLE
Extend CUDA version support

### ISSUE THREAD

**Issue by marcinz** [conda-forge/libcusolvermp-feedstock#2]
### Comment:

The current package requires CUDA >= 12.6. The `libcal` package supports CUDA >= 12.0. Would it be possible to make cusolvermp support CUDA >= 12.0 as well?

**Comment by carterbox** [comment]
Yes, this is possible [and is described here](https://github.com/conda-forge/cuda-feedstock/blob/main/recipe/doc/recipe_guide.md#cuda-enhanced-compatibility).

Do you mean CUDA >= 12.1.1? That's what [the docs claim for compatibility](https://docs.nvidia.com/cuda/cusolvermp/getting_started/index.html#software-requirements).

**Comment by marcinz** [comment]
I asked on the cusolverMp dev channel, and it seems that CUDA >= 12.0 should work.

**Comment by jakirkham** [comment]
For a CUDA 12+ recipe, this is what this would look like

```yaml
build:
  ...
  ignore_run_exports_from:
    # Ignore `cuda-version` constraint as this supports CUDA Enhanced Compatibility.
    - {{ compiler("cuda") }}
  ...

requirements:
  build:
    ...
    - {{ compiler("cuda") }}
    ...
  host:
    - cuda-version {{ cuda_compiler_version }}
    ...
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    ...
...
```

Examples to look at are [`nccl`]( https://github.com/conda-forge/nccl-feedstock/blob/d6cb47b6040eab6b5053482e2d3ef6ff047163d0/recipe/meta.yaml ) and [`ucx`]( https://github.com/conda-forge/ucx-split-feedstock/blob/cac169c575509c45856321b959fcdaa2c76e994f/recipe/meta.yaml )
